spring:
  application:
    name: refinement-login
  profiles:
    active: @profileActive@
  cloud:
    nacos:
      discovery:
        server-addr: @nacos.serverAddr@
server:
  port: 9002
  servlet:
    context-path: /login-center