spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zjzyinner_projectmanage?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: NYTwYL508B7sWYVU
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
#redis
  redis:
    database: 0
    port: @redis.port@
    host: @redis.host@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#mybatisplus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.refinement.entity
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)